### ISSUE TITLE
Basic Example?

### ISSUE THREAD

**Issue by thebetterjort** [hgranlund/passport-keycloak-bearer#1]
Do you have a basic example of this working? I'm trying to use this strategy with Hasura like this https://github.com/hasura/graphql-engine/blob/master/community/boilerplates/auth-servers/passportjs-jwt-roles/config/passport.js

**Comment by hgranlund** [comment]
I am not familiar with Hasura, but you find a sample in the [README](https://github.com/hgranlund/passport-keycloak-bearer/blob/master/README.md).

I created another example below, that extracts the email, username and realm_roles from the access-token. 
```js
const BearerStrategy = require('passport-keycloak-bearer');
const passport = require('passport');

passport.use(new BearerStrategy(({
  "realm": "master",
  "url": "https://keycloak.dev.com/auth"
}, (accessToken, done) => {
  if (!accessToken) {
    done('Unable to get token');
  }
  const { roles } = accessToken.realm_access || {};
  const {email, unique_name } = accessToken;
  const user = new User(unique_name, email, roles);
  done(null, user);
})));
```
