### ISSUE TITLE
Question: Request object in auth callback?

### ISSUE THREAD

**Issue by StevenLangbroek** [hgranlund/passport-keycloak-bearer#4]
Hey folks!

Currently we've manually wired our service up to keycloak, because we need to do some bookkeeping work after a user is redirected. The flow goes something like this:

- User registers, `redirect_uri` contains a `state` query param
- After creating a password through Keycloak, they log in and are redirected to above uri
- We decode the `state` query param, and use it to do some bookkeeping (i.e., call some endpoints, send some welcome emails)

Best I can tell this is not that uncommon of a workflow for this kind of authentication. What we'd need to get rid of our custom work, and be most useful for others I think, would be to give access to the `request` object in the callback.

I'd be willing to implement this, would you be open to a MR with this feature?

Thanks ❤️

**Comment by samdidos** [comment]
There is an option for this, pretty sure is what you looking for :

> passReqToCallback (Optional - Default: false)
> 
> Whether you want to use req as the first parameter in the verify callback. See section 5.1.1.3 for more details.

**Comment by StevenLangbroek** [comment]
Doh! I'm so sorry haha. Thanks!
