### ISSUE TITLE
Not securing by client

### ISSUE THREAD

**Issue by samdidos** [hgranlund/passport-keycloak-bearer#5]
Hi, I'm doing a simple case where I want to secure my API with a bearer token using Keycloak, but I want to secure a particular client and I don't see anything related to the client in the configuration. Is my usecase possible with this library?

**Comment by hgranlund** [comment]
What do you mean by client? 

You can easily secure different routes of your api. See the [passport.js documentation](http://www.passportjs.org/docs/) for more information.

**Comment by samdidos** [comment]
I meant Keycloak client, like a bearer-only client dedicated to my API. I know that we can still validate token only with the realm .well-known urls like userInfo, but I thought there was also some security to be sure that the request is coming from a particular client (like valid redirect URLs in a public client), but it doesn't seems so. Sorry, it seems that I still need to understand more how Keycloak works first.

**Comment by hgranlund** [comment]
Ah, you want to specify which user have access to which client? 

This is something keycloak should solve for you, but it looks like it is not straightforward.
I think one way is to add a custom script to the [authentication flow](https://www.keycloak.org/docs/7.0/server_admin/#_authentication-flows) you are using (e.g. Browser flow). The script could validate that the user have access to the client. For example by checking that the user has  a role belonging to the client. 

A script that, validates that the user has at least one role defined by the client, could look like this: 

```
//keycloak v7.x
function authenticate(context) {
  var username = user ? user.username : 'a unknown user';
  var client = session.getContext().getClient();
  
  var clientRoles = client.getRoles();
  var hasClientRole = false;
  for each(var role in clientRoles){
    hasClientRole = user.hasRole(role) || hasClientRole;
  }

  if (!hasClientRole) {
    LOG.info('User ' + username + ' does not have any role in client: ' + client.getClientId());
    var form = context.form();
    form.setError('A message to the user', null);
    context.clearUser();
    context.challenge(form.createLogin());
    return;
  }

  context.success();
}
```
