### ISSUE TITLE
Unable to import the library

### ISSUE THREAD

**Issue by Enkosz** [hgranlund/passport-keycloak-bearer#6]
Hi! I've been downloaded your library since i'm implementing it with a NestJS application.
Actually i'm implementing it as passport strategy inside my application but i don't know why when i try to use the ES6 library import style i got an undefined instead the Strategy class.

```
import KeycloakBearerStrategy from "passport-keycloak-bearer";

console.log(KeycloakBearerStrategy);

11:19:00 PM - Found 0 errors. Watching for file changes.
undefined <--- KeycloakBearerStrategy

```

i've installed it and double checked since it's in my node_modules (i've also tried to import it from the node_modules manually and still doesn't work any tips?

I've double checked it and it seems that the ES6 module import style doesn't work (import {} from "") with the require function it worked. Any idea why?

**Comment by hgranlund** [comment]
Hi,

Hmm strange, since this  works on all other projects. 
Can you provide a minimal examples of your setup? 

Thanks
