### ISSUE TITLE
Help with 401 unauthorized?

### ISSUE THREAD

**Issue by pdu7** [hgranlund/passport-keycloak-bearer#9]
Hi,

I'm not too familiar with keycloak and passport, but I'm trying to get a basic example up and running and I can't seem to get authenticated.

Here is my simple index.js file :

```javascript
const express = require('express');
const app = express();
const passport = require('passport');
const KeycloakBearerStrategy = require('passport-keycloak-bearer');

app.use(passport.initialize());
app.use(passport.session());

passport.use(new KeycloakBearerStrategy({
  realm: "master",
  url: "http://myKeycloakServer.com:4008/auth",
  loggingLevel: "debug"
}, (jwtPayload, done) => {
  // const user = doSomethingWithUser(jwtPayload);
  console.log('jwtPayload: \n',jwtPayload);
  return done(null, jwtPayload);
}));

app.get('/', (req, res) => {
  res.send("Server is up!");
});

app.get('/kc-test', passport.authenticate('keycloak', { session: false }), (req, res) => {
  res.send('success');
} )

app.listen(3000);
```

My client config is here 
![Screen Shot 2020-08-21 at 4 39 45 PM](https://user-images.githubusercontent.com/27778956/90932553-f31fc300-e3cc-11ea-8406-890ab681357e.png)

I'm trying to access my api using the bearer token I get from this curl request

curl -X POST 'http://myKeycloakServer.com:4008/auth/realms/master/protocol/openid-connect/token' \
 --header 'Content-Type: application/x-www-form-urlencoded' \
 --data-urlencode 'grant_type=password' \
 --data-urlencode 'client_id=mytestclient' \
 --data-urlencode 'client_secret=mytestclientssecret' \
 --data-urlencode 'username=mytestuser' \
 --data-urlencode 'password=mytestpassword'

I get this 401 unauthorized when making a simple get request to my api's /kc-test route.
![Screen Shot 2020-08-21 at 4 36 49 PM](https://user-images.githubusercontent.com/27778956/90932396-915f5900-e3cc-11ea-95d9-188fa62b862d.png)

My console for my API spits this out :

16:28:34.961 DEBUG KeycloakBearerStrategy - Strategy created
16:28:38.568 DEBUG KeycloakBearerStrategy - Got token with kid: 7DZcDdPpmQINrfvwVp-spJHxle8548ppRMWDeqJjWs8

My Keycloak Admin Console events shows this :
![Screen Shot 2020-08-21 at 4 45 41 PM](https://user-images.githubusercontent.com/27778956/90933651-e9e32600-e3cd-11ea-90bb-9e69137a843a.png)

What am I doing wrong? I'm able to successfully retrieve a token, but using it still results in 401 unauthorized. I would really appreciate your help :)

**Comment by hgranlund** [comment]
Sorry for my late response. 

Have you solved this jet?

**Comment by pdu7** [comment]
No, we ended up going with Keycloak Gatekeeper instead.

**Comment by M4RC0Sx** [comment]
Hi. I am having problems with a similar setup too. I used https://github.com/keycloak/keycloak-nodejs-connect and it worked perfectly, but I want to switch to other library because this is getting deprecated. Could you help me?

My code is mostly the same than the above.

**Comment by peilong-du** [comment]
Sorry, we ended up switching solutions and never figured out the bug.

**Comment by Shurtu-gal** [comment]
@hgranlund a little help here. Same problem
